export const ADD_TARGET = "ADD-TARGET";
export const REMOVE_TARGET = "REMOVE-TARGET";
export const EDIT_TARGET = "EDIT-TARGET";
export const COMPLETE_TARGET = "COMPLETE-TARGET"; 
export const SET_TARGET_EXPIRED = "SET-TARGET-EXPIRED";
export const SHOW_TARGET_DETAILS = "SHOW-TARGET-DETAILS";
export const UPLOAD_TARGETS = "UPLOAD_TARGETS";